name              'osl-idm'
maintainer        'Oregon State University'
maintainer_email  'chef@osuosl.org'
license           'All Rights Reserved'
description       'Installs/Configures osl-idm'
issues_url        'https://github.com/osuosl-cookbooks/osl-idm/issues'
source_url        'https://github.com/osuosl-cookbooks/osl-idm'
chef_version      '>= 18.0'
version           '0.1.0'

supports          'almalinux', '~> 8.0'
supports          'almalinux', '~> 9.0'
supports          'debian', '~> 12.0'
supports          'ubuntu', '~> 24.04'
