name             'test-idm'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'Apache-2.0'
description      'Installs/Configures test-idm'
version          '0.1.0'
depends          'osl-acme'
depends          'osl-idm'
depends          'osl-mysql', '>= 6.13.2'
depends          'line'
