# Stage 1: build (augmentation)
FROM quay.io/keycloak/keycloak:latest AS builder

# Enable key production features
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_DB=<%= @db_engine %>

WORKDIR /opt/keycloak

# Build optimized server
RUN /opt/keycloak/bin/kc.sh build

# Stage 2: runtime
FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/

# Set runtime-specific defaults
ENV KC_DB=<%= @db_engine %>
ENV KC_DB_URL=<%= @db_url %>
ENV KC_DB_USERNAME=<%= @db_user %>
ENV KC_DB_PASSWORD=<%= @db_pass %>
ENV KC_HOSTNAME=<%= @hostname %>

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
